-- BeEducated Dashboard & Reports Schema
-- Phase 6: Analytics, reports, and dashboard support
-- Run this in Supabase SQL Editor AFTER migrations 001-005

-- =============================================
-- ANALYTICS TABLES
-- =============================================

-- Daily aggregated statistics (pre-computed for performance)
CREATE TABLE daily_stats (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  stat_date DATE NOT NULL,

  -- User stats
  total_users INT DEFAULT 0,
  new_users INT DEFAULT 0,
  active_users INT DEFAULT 0,

  -- Student stats
  total_students INT DEFAULT 0,
  new_students INT DEFAULT 0,
  active_students INT DEFAULT 0,

  -- Enrollment stats
  new_enrollments INT DEFAULT 0,
  total_enrollments INT DEFAULT 0,

  -- Exam stats
  exams_conducted INT DEFAULT 0,
  exam_attempts INT DEFAULT 0,
  exams_passed INT DEFAULT 0,
  exams_failed INT DEFAULT 0,
  avg_exam_score DECIMAL(5, 2) DEFAULT 0,

  -- Content stats
  content_views INT DEFAULT 0,
  content_completions INT DEFAULT 0,

  -- Revenue stats (will be populated when payment module is added)
  revenue DECIMAL(12, 2) DEFAULT 0,
  payments_count INT DEFAULT 0,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE(stat_date)
);

-- Student performance tracking (for detailed analytics)
CREATE TABLE student_performance (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- Overall stats
  total_exams_attempted INT DEFAULT 0,
  total_exams_passed INT DEFAULT 0,
  total_exams_failed INT DEFAULT 0,
  average_score DECIMAL(5, 2) DEFAULT 0,
  highest_score DECIMAL(5, 2) DEFAULT 0,
  lowest_score DECIMAL(5, 2) DEFAULT 0,

  -- Subject-wise performance stored as JSONB
  -- Format: { "subject_id": { "attempts": 5, "avg_score": 75.5, "highest": 90 } }
  subject_performance JSONB DEFAULT '{}',

  -- Topic-wise weak areas
  -- Format: { "topic_id": { "correct": 10, "incorrect": 15, "accuracy": 40 } }
  topic_performance JSONB DEFAULT '{}',

  -- Streak and engagement
  current_streak INT DEFAULT 0,
  longest_streak INT DEFAULT 0,
  last_active_date DATE,
  total_study_time_minutes INT DEFAULT 0,

  -- Content progress
  videos_watched INT DEFAULT 0,
  notes_read INT DEFAULT 0,
  total_content_completed INT DEFAULT 0,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE(student_id)
);

-- Activity log for detailed tracking
CREATE TABLE activity_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id) ON DELETE SET NULL,

  -- Activity details
  activity_type VARCHAR(50) NOT NULL, -- login, logout, exam_start, exam_submit, content_view, etc.
  entity_type VARCHAR(50), -- exam, content, course, etc.
  entity_id UUID,

  -- Additional metadata
  metadata JSONB DEFAULT '{}',

  -- Context
  ip_address INET,
  user_agent TEXT,

  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Report generation tracking
CREATE TABLE generated_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Report info
  report_type VARCHAR(50) NOT NULL, -- student_performance, batch_report, revenue, exam_analysis
  report_name VARCHAR(255) NOT NULL,
  description TEXT,

  -- Filters used
  filters JSONB DEFAULT '{}',

  -- Date range
  start_date DATE,
  end_date DATE,

  -- Generated file
  file_url TEXT,
  file_format VARCHAR(10) DEFAULT 'pdf', -- pdf, csv, xlsx
  file_size_bytes INT,

  -- Status
  status VARCHAR(20) DEFAULT 'pending', -- pending, processing, completed, failed
  error_message TEXT,

  -- Generated by
  generated_by UUID REFERENCES users(id) ON DELETE SET NULL,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ
);

-- =============================================
-- INDEXES
-- =============================================

CREATE INDEX idx_daily_stats_date ON daily_stats(stat_date DESC);
CREATE INDEX idx_student_performance_student ON student_performance(student_id);
CREATE INDEX idx_student_performance_avg_score ON student_performance(average_score DESC);
CREATE INDEX idx_activity_logs_user ON activity_logs(user_id);
CREATE INDEX idx_activity_logs_type ON activity_logs(activity_type);
CREATE INDEX idx_activity_logs_created ON activity_logs(created_at DESC);
CREATE INDEX idx_activity_logs_entity ON activity_logs(entity_type, entity_id);
CREATE INDEX idx_generated_reports_type ON generated_reports(report_type);
CREATE INDEX idx_generated_reports_user ON generated_reports(generated_by);
CREATE INDEX idx_generated_reports_status ON generated_reports(status);

-- =============================================
-- RLS POLICIES
-- =============================================

ALTER TABLE daily_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_performance ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE generated_reports ENABLE ROW LEVEL SECURITY;

-- Daily stats - Admin only
CREATE POLICY "Admins can view daily stats" ON daily_stats
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM users WHERE id = auth.uid() AND role = 'admin'
    )
  );

CREATE POLICY "System can manage daily stats" ON daily_stats
  FOR ALL USING (true);

-- Student performance - Students see own, teachers see their students, admins see all
CREATE POLICY "Students view own performance" ON student_performance
  FOR SELECT USING (student_id = auth.uid());

CREATE POLICY "Teachers view student performance" ON student_performance
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM users WHERE id = auth.uid() AND role IN ('teacher', 'admin')
    )
  );

CREATE POLICY "System can manage student performance" ON student_performance
  FOR ALL USING (true);

-- Activity logs - Users see own, admins see all
CREATE POLICY "Users view own activity" ON activity_logs
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "Admins view all activity" ON activity_logs
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM users WHERE id = auth.uid() AND role = 'admin'
    )
  );

CREATE POLICY "System can insert activity logs" ON activity_logs
  FOR INSERT WITH CHECK (true);

-- Generated reports - Only creator and admins
CREATE POLICY "Users view own reports" ON generated_reports
  FOR SELECT USING (generated_by = auth.uid());

CREATE POLICY "Admins view all reports" ON generated_reports
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM users WHERE id = auth.uid() AND role = 'admin'
    )
  );

CREATE POLICY "System can manage reports" ON generated_reports
  FOR ALL USING (true);

-- =============================================
-- FUNCTIONS FOR ANALYTICS
-- =============================================

-- Function to update daily stats
CREATE OR REPLACE FUNCTION update_daily_stats(p_date DATE DEFAULT CURRENT_DATE)
RETURNS void AS $$
DECLARE
  v_total_users INT;
  v_new_users INT;
  v_total_students INT;
  v_new_students INT;
  v_new_enrollments INT;
  v_total_enrollments INT;
  v_exams_conducted INT;
  v_exam_attempts INT;
  v_exams_passed INT;
  v_avg_score DECIMAL(5,2);
BEGIN
  -- Count total users
  SELECT COUNT(*) INTO v_total_users FROM users WHERE is_active = true;

  -- Count new users for the date
  SELECT COUNT(*) INTO v_new_users
  FROM users WHERE DATE(created_at) = p_date;

  -- Count total students
  SELECT COUNT(*) INTO v_total_students
  FROM users WHERE role = 'student' AND is_active = true;

  -- Count new students for the date
  SELECT COUNT(*) INTO v_new_students
  FROM users WHERE role = 'student' AND DATE(created_at) = p_date;

  -- Count enrollments
  SELECT COUNT(*) INTO v_new_enrollments
  FROM course_enrollments WHERE DATE(enrolled_at) = p_date;

  SELECT COUNT(*) INTO v_total_enrollments FROM course_enrollments;

  -- Count exams conducted
  SELECT COUNT(*) INTO v_exams_conducted
  FROM exams WHERE DATE(start_time) = p_date AND status IN ('live', 'completed');

  -- Count exam attempts
  SELECT COUNT(*) INTO v_exam_attempts
  FROM exam_attempts WHERE DATE(started_at) = p_date;

  -- Count passed exams
  SELECT COUNT(*) INTO v_exams_passed
  FROM exam_results
  WHERE DATE(calculated_at) = p_date AND is_passed = true;

  -- Calculate average score
  SELECT COALESCE(AVG(percentage_score), 0) INTO v_avg_score
  FROM exam_results WHERE DATE(calculated_at) = p_date;

  -- Upsert daily stats
  INSERT INTO daily_stats (
    stat_date,
    total_users, new_users,
    total_students, new_students,
    new_enrollments, total_enrollments,
    exams_conducted, exam_attempts, exams_passed,
    avg_exam_score
  ) VALUES (
    p_date,
    v_total_users, v_new_users,
    v_total_students, v_new_students,
    v_new_enrollments, v_total_enrollments,
    v_exams_conducted, v_exam_attempts, v_exams_passed,
    v_avg_score
  )
  ON CONFLICT (stat_date) DO UPDATE SET
    total_users = EXCLUDED.total_users,
    new_users = EXCLUDED.new_users,
    total_students = EXCLUDED.total_students,
    new_students = EXCLUDED.new_students,
    new_enrollments = EXCLUDED.new_enrollments,
    total_enrollments = EXCLUDED.total_enrollments,
    exams_conducted = EXCLUDED.exams_conducted,
    exam_attempts = EXCLUDED.exam_attempts,
    exams_passed = EXCLUDED.exams_passed,
    avg_exam_score = EXCLUDED.avg_exam_score,
    updated_at = NOW();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to update student performance after exam
CREATE OR REPLACE FUNCTION update_student_performance_on_result()
RETURNS TRIGGER AS $$
DECLARE
  v_student_id UUID;
  v_subject_id UUID;
BEGIN
  -- Get student_id from attempt
  SELECT student_id INTO v_student_id
  FROM exam_attempts WHERE id = NEW.attempt_id;

  -- Get subject_id from exam
  SELECT subject_id INTO v_subject_id
  FROM exams e
  JOIN exam_attempts ea ON e.id = ea.exam_id
  WHERE ea.id = NEW.attempt_id;

  -- Update or insert student performance
  INSERT INTO student_performance (student_id)
  VALUES (v_student_id)
  ON CONFLICT (student_id) DO NOTHING;

  -- Update aggregate stats
  UPDATE student_performance
  SET
    total_exams_attempted = total_exams_attempted + 1,
    total_exams_passed = total_exams_passed + CASE WHEN NEW.is_passed THEN 1 ELSE 0 END,
    total_exams_failed = total_exams_failed + CASE WHEN NOT NEW.is_passed THEN 1 ELSE 0 END,
    average_score = (
      SELECT AVG(percentage_score)
      FROM exam_results er
      JOIN exam_attempts ea ON er.attempt_id = ea.id
      WHERE ea.student_id = v_student_id
    ),
    highest_score = GREATEST(highest_score, NEW.percentage_score),
    lowest_score = CASE
      WHEN lowest_score = 0 THEN NEW.percentage_score
      ELSE LEAST(lowest_score, NEW.percentage_score)
    END,
    last_active_date = CURRENT_DATE,
    updated_at = NOW()
  WHERE student_id = v_student_id;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for updating student performance
DROP TRIGGER IF EXISTS trigger_update_student_performance ON exam_results;
CREATE TRIGGER trigger_update_student_performance
  AFTER INSERT ON exam_results
  FOR EACH ROW
  EXECUTE FUNCTION update_student_performance_on_result();

-- Function to log activity
CREATE OR REPLACE FUNCTION log_activity(
  p_user_id UUID,
  p_activity_type VARCHAR(50),
  p_entity_type VARCHAR(50) DEFAULT NULL,
  p_entity_id UUID DEFAULT NULL,
  p_metadata JSONB DEFAULT '{}'
)
RETURNS UUID AS $$
DECLARE
  v_log_id UUID;
BEGIN
  INSERT INTO activity_logs (user_id, activity_type, entity_type, entity_id, metadata)
  VALUES (p_user_id, p_activity_type, p_entity_type, p_entity_id, p_metadata)
  RETURNING id INTO v_log_id;

  RETURN v_log_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =============================================
-- VIEWS FOR REPORTING
-- =============================================

-- Top performing students view
CREATE OR REPLACE VIEW top_students AS
SELECT
  sp.student_id,
  u.full_name,
  u.email,
  sp.total_exams_attempted,
  sp.total_exams_passed,
  sp.average_score,
  sp.highest_score,
  sp.current_streak,
  CASE
    WHEN sp.total_exams_attempted > 0
    THEN ROUND((sp.total_exams_passed::DECIMAL / sp.total_exams_attempted) * 100, 2)
    ELSE 0
  END AS pass_percentage
FROM student_performance sp
JOIN users u ON sp.student_id = u.id
WHERE u.is_active = true
ORDER BY sp.average_score DESC;

-- Batch performance summary view
CREATE OR REPLACE VIEW batch_performance_summary AS
SELECT
  b.id AS batch_id,
  b.name AS batch_name,
  COUNT(DISTINCT bm.student_id) AS total_students,
  COUNT(DISTINCT ea.id) AS total_exam_attempts,
  COALESCE(AVG(er.percentage_score), 0) AS avg_score,
  COUNT(CASE WHEN er.is_passed THEN 1 END) AS passed_count,
  COUNT(CASE WHEN er.is_passed = false THEN 1 END) AS failed_count
FROM batches b
LEFT JOIN batch_members bm ON b.id = bm.batch_id AND bm.status = 'active'
LEFT JOIN exam_attempts ea ON bm.student_id = ea.student_id
LEFT JOIN exam_results er ON ea.id = er.attempt_id
WHERE b.is_active = true
GROUP BY b.id, b.name;

-- Course enrollment summary view
CREATE OR REPLACE VIEW course_enrollment_summary AS
SELECT
  c.id AS course_id,
  c.name AS course_name,
  c.code AS course_code,
  COUNT(DISTINCT ce.student_id) AS enrolled_students,
  COUNT(DISTINCT CASE WHEN ce.status = 'active' THEN ce.student_id END) AS active_students,
  COUNT(DISTINCT CASE WHEN ce.status = 'completed' THEN ce.student_id END) AS completed_students,
  COALESCE(AVG(ce.progress), 0) AS avg_progress
FROM courses c
LEFT JOIN course_enrollments ce ON c.id = ce.course_id
WHERE c.is_active = true
GROUP BY c.id, c.name, c.code;

-- Daily growth view
CREATE OR REPLACE VIEW daily_growth AS
SELECT
  stat_date,
  new_users,
  new_students,
  new_enrollments,
  revenue,
  LAG(new_users) OVER (ORDER BY stat_date) AS prev_new_users,
  LAG(new_students) OVER (ORDER BY stat_date) AS prev_new_students,
  LAG(revenue) OVER (ORDER BY stat_date) AS prev_revenue
FROM daily_stats
ORDER BY stat_date DESC;

-- =============================================
-- INITIAL DATA
-- =============================================

-- Insert today's stats placeholder
INSERT INTO daily_stats (stat_date)
VALUES (CURRENT_DATE)
ON CONFLICT (stat_date) DO NOTHING;

COMMENT ON TABLE daily_stats IS 'Pre-computed daily statistics for dashboard performance';
COMMENT ON TABLE student_performance IS 'Aggregated student performance metrics';
COMMENT ON TABLE activity_logs IS 'User activity tracking for analytics';
COMMENT ON TABLE generated_reports IS 'Tracking for generated report files';
